language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8
  
before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - drush make vimi_dk.build ../vimi.dk
  - cd ../vimi.dk
  - sudo chmod -R 777 sites/all/modules
  - php -d sendmail_path=/dev/null `which drush` vimi_dk --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="vimi.dk" --yes
  - drush cc all --yes

script: 
  - test -d profiles/vimi_dk
  - test -d profiles/vimi_dk/modules/contrib
  - test -d profiles/vimi_dk/themes
